/*
    This is the routiute for going to bed and to send a message to the user when to do they things
     
    The Goal or what the program is gonna be for.
    @Author
     @Date
     These things should go at the Start of the code.
*/
               
var testtime = 6
// Create Variables[String:Message &message1& Message2 & Message3, Datetime:CurrentTime, Number:Timer, Bool:onOff] 
var message = "Brush Teeth";
var message1 = "Contunie doing your things";
var message2 = "Say Goodnight";
var message3 = "Into bed and sleep";
// Message = “Brush Teeth”
// Message1= “Countie doing your thing”
// Message2 = “Say Goodnight”
// Message3 = “Into bed and sleep”
var currettime = testtime;
// Currenttime = Time
var Timer = 3;
// Timer = Set number to 300 seconds
var on = true;
var off = false;
// On = True
// Off = False
if (currettime = 9)
    {
        print(message)
    }
    else{
        print(message1)
    }
// If Current Time = 21:30
// 	Print (message) && 	Start Timer
// Else Loop
// Then If timer ends
// 	Print(“Stop” + message + “ and do ”+ message2) 
// Else
// Continue unit timer ends

// Then If On = false
// 	Print (message3)
// 	END	
// Else
// 	Print(“Turn off light” On = false)
// 	END
	

